### ISSUE TITLE
[ w4-ETL-Project](Paula Bendito Buhles)

### ISSUE THREAD

**Issue by paulabnbh** [Ironhack-Data-Madrid-Enero-2023/w4-ETL-Project#1]
https://github.com/paulabnbh/ETL-project

**Comment by OrianAmpuero** [comment]
Muy bien Paula, has trabajado correctamente todo el proceso del proyecto!! Me faltó ver el ERD de SQL, si lo tienes adjúntalo y como sé que puedes dar más te aconsejo que hagas insights. De resto bien hecho :)
