### ISSUE TITLE
[ w4-ETL-Project](Alvaro Lorenzo)

### ISSUE THREAD

**Issue by alorenzoti** [Ironhack-Data-Madrid-Enero-2023/w4-ETL-Project#10]
https://github.com/alorenzoti/Proyecto_ETL

**Comment by fjgarciaes** [comment]
Buen trabajo Alvaro, has seguido las indicaciones que se pedían para completar el proyecto y tanto la extracción como la limpieza tiene sentido y esta bien hecho. Trata de hacer el readme un poco mas visual y hablando un poco mas de tu propio proyecto en sí. Sigue así
