### ISSUE TITLE
[exoplanet-proyecto](Amin)

### ISSUE THREAD

**Issue by aminmadrileno** [Ironhack-Data-Madrid-Enero-2023/w4-ETL-Project#11]
https://github.com/aminmadrileno/Exoplanet-ETL

**Comment by aminmadrileno** [comment]
https://github.com/aminmadrileno/Exoplanet-ETL

**Comment by fjgarciaes** [comment]
Muy buen trabajo Amin! Se ve que has realizado un muy buen trabajo de extracción que no era sencillo y te felicito por ello. No veo la carga de los archivo  a SQL ( no se si lo habrás hecho). Se ha vuelto a subir tu token a GitHub. Trata de subir los archivos en carpetas y hacer el readme un poco mas llamativo ( si te resulta mas sencillo puedes hacerlo en inglés) 
En cuanto a la presentación te felicito por como lo has hecho sabiendo que el español es un elemento extra para ti, trata no hablar de las cosas que no te han salido como querías. En general, excelente proyecto, sigue así.
