### ISSUE TITLE
w4-ETL-Project (Axel Girou

### ISSUE THREAD

**Issue by AxelCrypto** [Ironhack-Data-Madrid-Enero-2023/w4-ETL-Project#12]
https://github.com/AxelCrypto/IMF-Impact

**Comment by fjgarciaes** [comment]
Excelente trabajo Axel!! Has seguido todas las indicaciones que se pedían y has realizado un buen trabajo en todos los pasos del proyecto. El readme esta bien, con muchas imágenes y gráficas, aunque quizás demasiadas, igual estaría mejor si pusieses las más significativas y hubiese un poco menos de texto. En cuanto a la presentación muy bien, has manejado bien el espacio, aunque quizás te has extendido un poco a la hora de explicar las gráficas pero en general muy bien.
