### ISSUE TITLE
[NFL Penalties ETL] (Carlos Mato)

### ISSUE THREAD

**Issue by CharlyKill7** [Ironhack-Data-Madrid-Enero-2023/w4-ETL-Project#15]
https://github.com/CharlyKill7/NFL-Penalties_ETL

**Comment by fjgarciaes** [comment]
Muy buen trabajo Carlos. Me parece un proyecto interesante y se ve que hay trabajo en todos los requerimientos que se pedían y un buen trabajo de los datos. El readme esta muy bien y es bastante explicativo aunque quizas contiene demasiado texto en algunas partes como en el proceso de extracción. Intenta meter los archivos en carpetas para que quede más limpio el repo.El análisis del bonus me ha parecido muy interesante. Te felicito por el trabajo que has realizado en este proyecto, sigue así.
