### ISSUE TITLE
[ w4-ETL-Project](Jorge Freire)

### ISSUE THREAD

**Issue by jorgefreires** [Ironhack-Data-Madrid-Enero-2023/w4-ETL-Project#16]
https://github.com/jorgefreires/Madrid-polution-ETL-project.git

Saque 133 archivos .csv pero de una misma página web. No me he dado cuenta del error de que tenían que ser diferentes urls hasta que ya era tarde. Espero que el trabajo sea valido igualmente, descargar y juntar los 133 archivos .csv llevo su tiempo.

**Comment by fjgarciaes** [comment]
Buen trabajo Jorge! La idea del proyecto esta bien y el trabajo que has realizado también pero como tu mismo te diste cuenta las restricciones que se pusieron para este proyecto eran otras así que te animo a intentar encontrar datos de otras fuentes.
