### ISSUE TITLE
w4-ETL-Project (Lohengrin Verde)

### ISSUE THREAD

**Issue by lohe040789** [Ironhack-Data-Madrid-Enero-2023/w4-ETL-Project#17]
https://github.com/lohe040789/Proyecto-ETL

**Comment by OrianAmpuero** [comment]
Bien Lohe! En cuanto al repo, recuerda tener todo en carpetas y mejorar el readme que es la cara del proyecto. Buen curro lo de la extracción y sé que puedes seguir trabajando en ello.
