### ISSUE TITLE
[w4-ETL-Project](Rafael Calbacho)

### ISSUE THREAD

**Issue by Calbacho** [Ironhack-Data-Madrid-Enero-2023/w4-ETL-Project#18]
https://github.com/Calbacho/ETL-Project

**Comment by OrianAmpuero** [comment]
Muy bien Rafa!! Excelente trabajo de ETL. En cuanto al repo bien organizado (cuidado que hay un archivo suelto, para que lo metas en una de las carpetas) y muy bien el readme, solo que trata de no poner código y hay un detalle que pusiste 'fromato' entiendo que era 'formato'.
La presentación estuvo muy amena, bien los próximos pasos y las imágenes para apoyarte, así como la info para poner a todos en contexto.
