### ISSUE TITLE
[w4-ETL-Project](Ronald Hernandez)

### ISSUE THREAD

**Issue by Ronher1992** [Ironhack-Data-Madrid-Enero-2023/w4-ETL-Project#19]
https://github.com/Ronher1992/Project_ETL

**Comment by OrianAmpuero** [comment]
Bien Ronald! Falta proceso de extracción según lo pedido (3 fuentes) pero espero que sigas trabajando en ello; el repo tiene otro repo adjunto que aparece como copia, trata de acomodarlo. En cuanto a la presentación:
-no decir lo malo porque nadie lo sabe
-mucho texto, más imágenes de apoyo 

A seguir trabajando a tope!
