### ISSUE TITLE
[w4-ETL-Project](Jorge Mendoza)

### ISSUE THREAD

**Issue by jmgpgit** [Ironhack-Data-Madrid-Enero-2023/w4-ETL-Project#2]
https://github.com/jmgpgit/Scraping-Project

**Comment by OrianAmpuero** [comment]
Muy bien Jorge, has aplicado todo el proceso para este proyecto y bien hecho.. Recuerda tener todos los archivos en diferentes carpetas depende del contenido para que se vea mejor el repo.
