### ISSUE TITLE
ETL-Project (Fernando Amaya)

### ISSUE THREAD

**Issue by Patacabra** [Ironhack-Data-Madrid-Enero-2023/w4-ETL-Project#21]

**Comment by Patacabra** [comment]
https://github.com/Patacabra/ETLProject.git

**Comment by fjgarciaes** [comment]
Buen trabajo Fernando. Se ve que temas esforzado mucho para conseguir los datos que querías a pesar de las complicaciones que te han podido ir surgiendo y has realizado un buen trabajo con ellos. Trata de terminar el readme ya que creo que esta incompleto y definir un objetivo que ayude a entender que es lo que quieres hacer con estos datos, ademas de meter los datos en carpetas para que el repo este bonito y comenta un poco las conclusiones ya que solo con las gráficas se hace un poco difícil.
