### ISSUE TITLE
[ w4-ETL-Project](Cristina Apostol)

### ISSUE THREAD

**Issue by cristina-apostol** [Ironhack-Data-Madrid-Enero-2023/w4-ETL-Project#22]
https://github.com/cristina-apostol/ETL-PROJECT.git

Me acabo de dar cuenta, que al scrapear la pagina web de JustWatch la lista resultante no la acorté, y ya no lo podía modificar. Sorry:(

**Comment by fjgarciaes** [comment]
Muy buen trabajo Cristina y gracias por el comentario para saber que te diste cuenta. El trabajo cumple con todos los objetivos y esta muy bien, me gusta que vayas comentando el código para ver el proceso que sigues y como mientras vas trabajando te vas dando cuenta de cosas que puedes cambiar y como vas procediendo según las cosas que te vas dando cuenta. El readme esta bien también y el repo bien organizado. En cuanto a la presentación lo has hecho bien, no extendiéndote demasiado en las cosas que no necesitaban importancia pero trata de introducir mejor la presentación, presentándotela a ti y el proyecto. En general, muy buen trabajo, sigue así.
