### ISSUE TITLE
Proyecto ETL Paula Garcia

### ISSUE THREAD

**Issue by pgmar257** [Ironhack-Data-Madrid-Enero-2023/w4-ETL-Project#24]
https://github.com/pgmar257/Project-ETL

**Comment by OrianAmpuero** [comment]
Muy bien Paula!! La organización y el readme bien, en cuanto al código se ve el curro y sé que ha sido complicado pero estoy segura de que si sigues así vas a lograr ese proyectazo que quieres :)
