### ISSUE TITLE
[ETL-Project] (Bea Zatarain)

### ISSUE THREAD

**Issue by BeaZatarain** [Ironhack-Data-Madrid-Enero-2023/w4-ETL-Project#3]
https://github.com/BeaZatarain/ETL-Project

**Comment by fjgarciaes** [comment]
Excelente trabajo Bea! Has cumplido con todos los objetivos que se pedían a pesar de las dificultades que te has ido encontrando a lo largo del proyecto por lo que te felicito ya que el código esta bien y con sentido en base a lo que querías conseguir. No me queda muy claro que has hecho con la tercera fuente. El readme esta muy bien aunque quizás podrías acortar un poco la parte donde explicas la exploración y limpieza y tienes un archivo metido dentro de src y también fuera, échale un ojo. Sigue trabajando así que se nota el esfuerzo
