### ISSUE TITLE
[ w4-ETL-Project](Eduardo Pastor Ruiz)

### ISSUE THREAD

**Issue by Edupastore** [Ironhack-Data-Madrid-Enero-2023/w4-ETL-Project#5]
https://github.com/Edupastore/w4-ETL-Project

**Comment by fjgarciaes** [comment]
Muy buen trabajo Edu. Se ve que has trabajado mucho en este proyecto y has cumplido con todos los objetivos que te pedíamos. El proceso de transformación y limpieza de los datos se ve que te ha llevado su tiempo y has tenido que trabajar bastante para conseguir los datos como los querías pero en el readme trata de explicarlo de una manera mas corta y sin tratar de hablar de los problemas que te ha supuesto y sin meterte mucho en temas concretos como los cambios de nombres de columnas y demás. Sigue así y hazte con todos :)
