### ISSUE TITLE
w4-ETL-Project(jel)

### ISSUE THREAD

**Issue by jel-garay** [Ironhack-Data-Madrid-Enero-2023/w4-ETL-Project#6]
https://github.com/jel-garay/proyecto-Apis.git

**Comment by fjgarciaes** [comment]
Buen trabajo Jel, has conseguido todos los objetivos que se pedían para este proyecto y has trabajado todos los procesos que pedíamos. Intenta echarle un ojo al readme para ver el sentido que tienen algunas frases y trata de no incluir código.
