### ISSUE TITLE
[ETL-Project] (Cristian Gómez)

### ISSUE THREAD

**Issue by crisgo-data** [Ironhack-Data-Madrid-Enero-2023/w4-ETL-Project#8]
https://github.com/crisgo-data/ETL-project

**Comment by fjgarciaes** [comment]
Excelente trabajo Cristian. Me parece un proyecto muy interesante. Has cumplido con todos los objetivos que te pedíamos y en el código se puede ver que hay mucho trabajo y esfuerzo detrás. Intenta meter el archivo que contiene el código en una carpeta para que quede el repo bien. El readme esta muy bien explicado y con sentido. Felicidades por este trabajo, sigue así.

**Comment by crisgo-data** [comment]
Gracias Javi, que buen feedback, así dan ganas de seguir!!
