### ISSUE TITLE
[w4-ETL-Project](Alfonso Urra)

### ISSUE THREAD

**Issue by AlfonsoUrra** [Ironhack-Data-Madrid-Enero-2023/w4-ETL-Project#9]
https://github.com/AlfonsoUrra/-w4-ETL-Project-Alfonso-Urra-

**Comment by fjgarciaes** [comment]
Buen trabajo Alfonso, me parece un proyecto interesante y has cumplido con los objetivos que pedíamos. Trata en el readme de no poner las cosas que todavía no has realizado, quizas puedes poner un punto de pasos a seguir en el que puedes explicar la dirección que quieres que tome el proyecto y estaría bien si se pudiese ver la imagen del diagrama de SQL.
